# Generated by Django 4.2.2 on 2023-06-21 12:56

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('creation_date', models.DateField(blank=True, verbose_name='creation_date')),
                (
                    'rating',
                    models.FloatField(
                        blank=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('movie', 'Movie'), ('tv_show', 'Tv Show')], max_length=10, verbose_name='type'
                    ),
                ),
            ],
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies', 'db_table': 'film_work',},
        ),
    ]
